name: 🐛 Bug Report
description: Help us improve this repository by filing a detailed bug report.
title: '[bug]: '
labels: ['issue: bug', 'status: to be confirmed']
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the issue or unexpected behavior related to the Strapi Client.
      placeholder: Using the Strapi client to fetch data from the "articles" collection does not return the expected results.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed, step-by-step guide on how to reproduce the issue. Include code snippets or links to repositories if applicable.
      placeholder: |
        Example:
          1. Initialize a new Strapi project with an "article" collection type defined as "...".
          2. Configure the Strapi client with your Strapi API URL and authentication token.
          3. Perform a query to fetch entries from a collection: `client.collection('articles').find()`.
          4. Observe the unexpected behavior or error in the response/output.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Provide a detailed explanation of what you expected to happen instead of the observed issue. Be as specific as possible.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: The version of the Strapi Client that was used.
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Select the operating system where you are experiencing the issue.
      multiple: false
      options:
        - MacOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime Environment
      description: Select all runtime environments where the issue has occurred.
      multiple: true
      options:
        - Browser
        - Node.js
        - Bun
        - Deno
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If available, please provide the logs generated while using the client.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Media
      description: If available, please upload screenshots or videos to illustrate the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmation Checklist
      options:
        - label: I have checked the existing [issues](https://github.com/strapi/client/issues)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/strapi/client/blob/main/CODE_OF_CONDUCT.md)
          required: true

        - label: I would like to work on this issue
