name: 'Unit Tests'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: read

jobs:
  unit_tests:
    name: 'Unit Tests (node: ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: pnpm run test
